- name: Adding repository
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Install latest version of "python3.7"
  apt:
    update_cache: yes
    name: python3.7
    state: present
    install_recommends: yes
  notify: Handler_No1

- name: Remove python3.7
  apt:
    update_cache: yes
    name: python3.7
    state: absent
    install_recommends: yes
    autoremove: true
  notify: Handler_No1
